<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7EJ77M7" failures="1" tests="8" name="appium.runner.CalculatorDestroyerTwo" time="166.983" errors="0" timestamp="2022-09-23T13:49:50 ICT" skipped="0">
  <testcase classname="appium.runner.CalculatorDestroyerTwo" name="testPost" time="20.690"/>
  <system-out/>
  <testcase classname="appium.runner.CalculatorDestroyerTwo" name="testPost" time="20.646"/>
  <system-out/>
  <testcase classname="appium.runner.CalculatorDestroyerTwo" name="testPost" time="21.254"/>
  <system-out/>
  <testcase classname="appium.runner.CalculatorDestroyerTwo" name="testPost" time="19.195"/>
  <system-out/>
  <testcase classname="appium.runner.CalculatorDestroyerTwo" name="testPost" time="20.893"/>
  <system-out/>
  <testcase classname="appium.runner.CalculatorDestroyerTwo" name="testPost" time="23.879"/>
  <system-out/>
  <testcase classname="appium.runner.CalculatorDestroyerTwo" name="testPost" time="20.006">
    <failure message="expected [0.5555555555555556] but found [0.5555555555555555]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0.5555555555555556] but found [0.5555555555555555]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.testng.Assert.assertEquals(Assert.java:762)
at appium.runner.CalculatorDestroyerTwo.testPost(CalculatorDestroyerTwo.java:127)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testPost -->
  <system-out/>
  <testcase classname="appium.runner.CalculatorDestroyerTwo" name="testPost" time="20.420"/>
  <system-out/>
</testsuite> <!-- appium.runner.CalculatorDestroyerTwo -->
